### ISSUE TITLE
[MAUI][ANDROID] TabHostView Text Colors Don't Change Switching Light/Dark Mode

### ISSUE THREAD

**Issue by sk1llsh0t** [roubachof/Sharpnado.Tabs#131]
Platform (please complete the following information):

OS: [Android]
Device: Tab Active 3 [Android API Level 31]
Sdk Version: Min: 30 Target: 34
MAUI: [NET 8.0][8.0.91]

I notice the text colors for selected and unselected tabs aren't switching when the dark/light mode changes. The background color changes and the segmentedoutlinecolor changes. Something isn't working right with the text colors though when switching dark/light mode.

This issue was introduced after the fix for this issue (https://github.com/roubachof/Sharpnado.Tabs/issues/127#)

I'm currently on sharpnado.tabs 3.1.1

To Reproduce

    Create an app with the Tabs control
    In the Resources/Styles/Styles.xaml, add styling for the various tab components with AppThemeBindings for light and dark modes
    Run the app. while you are on the page with the tabs, tap around to make sure it is working.
    Then, from the notification tray, change the theme from light to dark or vice versa.
    Dismiss the notification tray after the theme has switched so you are back in the app.
    You'll notice as you switch the dark/light mode, the text colors in the tabhostview aren't changing

Styles used in my Style.xaml file: (of course change the color StaticResources to match your colors)

 <Style TargetType="sho:TabHostView" x:Key="TabHostView">
        <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource LightBackground02}, Dark={StaticResource DarkBackground02}}" />
        <Setter Property="SegmentedOutlineColor" Value="{AppThemeBinding Light={StaticResource Gray950}, Dark={StaticResource Gray200}}" />
        <Setter Property="CornerRadius" Value="10" />
        <Setter Property="TabType" Value="Fixed" />
        <Setter Property="IsSegmented" Value="True" />
        <Setter Property="Orientation" Value="Horizontal" />
        <Setter Property="SegmentedHasSeparator" Value="True" />
    </Style>
    
    <Style TargetType="sho:UnderlinedTabItem" x:Key="UnderlinedTabItem">
        <Setter Property="SelectedTabColor" Value="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource PrimaryLight}}" />
        <Setter Property="UnselectedLabelColor" Value="{AppThemeBinding Light={StaticResource LightSecondaryText}, Dark={StaticResource DarkSecondaryText}}" />
    </Style>
    
    <Style TargetType="sho:BadgeView" x:Key="BadgeView">
        <Setter Property="Background" Value="{StaticResource Secondary}"></Setter>
    </Style>

Expected Behavior: Tab text colors change to their respective dark/light theme color

**Comment by roubachof** [comment]
Look like a good first issue to me 😄

**Comment by roubachof** [comment]
I tried to fix that, but no idea why the property changed is not triggered on the tab item's property...

**Comment by sk1llsh0t** [comment]
It was working before 3.1.0/3.1.1.

**Comment by roubachof** [comment]
Oh cause we switched to .net 8 maybe

**Comment by sk1llsh0t** [comment]
I believe I know what is happening. Right now, you have an OnPropertiesChanged override that is handling all the property changes. It uses a switch statement to know which property changed and take the appropriate action. In my experience moving our app from xamarin forms to maui (.net 8.0), this no longer works consistently. Some properties it will fire for but others, not.

The way to do it is when instantiating the bindableproperty, there is a parameter for onpropertychanged which you can define a callback for. if you pass the method in through that parameter directly to the bindableproperty, it will work.

This is definitely a bug in maui that has not been addressed yet apparently. Give that a try and see if it starts working again.

**Comment by janusw** [comment]
> - In the Resources/Styles/Styles.xaml, add styling for the various tab components with AppThemeBindings for light and dark modes

Does this work at all for you? Whenever I try to style the tabs via Styles.xaml I get a strange exception (with 3.1.0 and 3.2.0 on Android):
```
System.NullReferenceException: Object reference not set to an instance of an object.
  at at Sharpnado.Tabs.TabHostView.UpdateTabType()
  at at Sharpnado.Tabs.TabHostView.OnPropertyChanged(String propertyName)
```

**Comment by sk1llsh0t** [comment]
it does work for me. the repro project i have posted above uses styles.xaml (https://github.com/sk1llsh0t/TabVmBindingRepro)

**Comment by sk1llsh0t** [comment]
So basically, you eliminate this method (https://github.com/roubachof/Sharpnado.Tabs/blob/07f3072e2496bd6c76e6b3e7250c61767524ff69/Tabs/Tabs/UnderlinedTabItemBase.cs#L39)

Then, you modify your bindableproperties to handle the property change. 
Example:
'''
public static readonly BindableProperty SelectedTabColorProperty = BindableProperty.Create(
            nameof(SelectedTabColor),
            typeof(Color),
            typeof(TabItem),
            Colors.Magenta,
            propertyChanged: OnPropertyChanged   // add this line to all your bindable properties
);

private static void OnPropertyChanged(BindableObject bindable, object oldValue, object newValue) 
{ 
        // Same logic from the old OnPropertyChanged but you'll need to look at the BindableObject to know what is changing
}
'''

**Comment by roubachof** [comment]
nope. Already tried what you suggested unfortunately

**Comment by sk1llsh0t** [comment]
Looks like maybe it is a MAUI issue with appthemebindings.
https://github.com/CommunityToolkit/Maui/issues/1994
https://github.com/dotnet/maui/issues/24444

Possible resolve commit:
https://github.com/dotnet/maui/pull/24465

I guess they broke it going from net6 to net8 since this was all working in 3.0.1 but broke in 3.1.0. So hopefully in a future release, this gets fixed.

**Comment by sk1llsh0t** [comment]
The issue was introduced in this commit: (https://github.com/roubachof/Sharpnado.Tabs/commit/c60990f72d523c38df60776d7a0004fff791256d)

In the TabHostView class, the frame control was changed to a border. Changing it back to a frame makes the app theme colors work again. 

To figure it out, i grabbed the previous good commit, and started adding each changed code section 1 at a time until it broke. Since the border was the last thing i thought would break something like this, it was the last remaining thing to check. Anyway, there you go.

**Comment by janusw** [comment]
> Does this work at all for you? Whenever I try to style the tabs via Styles.xaml I get a strange exception (with 3.1.0 and 3.2.0 on Android):
> 
> ```
> System.NullReferenceException: Object reference not set to an instance of an object.
>   at at Sharpnado.Tabs.TabHostView.UpdateTabType()
>   at at Sharpnado.Tabs.TabHostView.OnPropertyChanged(String propertyName)
> ```

FYI: I managed to reproduce it with the sample app and opened issue #138 for it.

**Comment by roubachof** [comment]
@sk1llsh0t nice job !
I will fix #138 and see what's what

**Comment by sk1llsh0t** [comment]
Any update on this one?

**Comment by roubachof** [comment]
I won't have any time on this one. I guess you are very close to find the issue after your recent findings:)

**Comment by roubachof** [comment]
Meaning: if you find the issue I will make a new package ASAP

**Comment by sk1llsh0t** [comment]
My opinion is something is broken in the border control that isn't allowing the property events to fire on child elements when dark/light mode changes. The only solution I can come up with is to revert the border back to a frame. Unfortunately, the frame control is flagged as obsolete in .net 9. It is possible that the maui folks need to take a look at this issue in the border control.

Anyway, i have a forked branch where i've reverted the border back to a frame. if you are ok with that, i can submit a pull request. This can be a temporary solution until the border is fixed.

Let me know.



Let me know i

**Comment by sk1llsh0t** [comment]
I don't have any more time to give to this much less wait on Microsoft to come up with a fix to their border control. I may wait until .Net 9 is released to see if that fixes it. Otherwise, without the ability to switch the app theming colors correctly, I may need to roll my own tabview or something.

You've done great work with this control. It is just a shame that something out of your control is causing this breaking issue.

**Comment by roubachof** [comment]
as a matter of fact you could intercept the Theme change event and set the color accordingly until MS fixes the issue.

**Comment by sk1llsh0t** [comment]
One other thing i noticed, if i set IsSegmented=False (no border), the colors work. then if i add the border around the tabhostview, the colors continue to work. So it looks like the issue is not there if xaml is used.

**Comment by gsgou** [comment]
reproducable also in iOS under Maui 10.0.100
