### ISSUE TITLE
[MAUI] CollectionView does not load unless I use a button.

### ISSUE THREAD

**Issue by PrestigiousF** [roubachof/Sharpnado.Tabs#74]
I have a CollectionView in my tab, and it doesn't populate unless I add a button and press it after the view is visible.
I've tried adding BindingContext to the LazyView, I've tried placing the Method in the xaml.cs after intitilzecomponent. The Collection is populated, but it doesn't show! Is the collection no longer existent after the view is loaded?

ExploreTab:
```
<tabs:LazyView x:TypeArguments="views:Shopping"
                          AccentColor="{StaticResource Secondary}"
                          Animate="True"
                          UseActivityIndicator="True"/>
```

ExploreTabViewModel:
```
public class ExploreTabViewModel
    {
        private int _selectedViewModelIndex = 0;

        public int SelectedViewModelIndex
        {
            get => _selectedViewModelIndex;
            set => ++_selectedViewModelIndex;
        } 

        public BarsViewModel BarsViewModel { get; }

        public RestaurantsViewModel RestaurantsViewModel { get; }

        public ThingsToDoViewModel ThingsToDoViewModel { get; }

        public ShoppingViewModel ShoppingViewModel { get; }

        public bool IsTabVisible { get; set; } = true;
    }
```

ShoppingTab:

```
<ContentView xyz>
    <ContentView.BindingContext>
        <viewmodels:ShoppingViewModel/>
    </ContentView.BindingContext>
    
    <Grid RowDefinitions="*">
    <CollectionView ItemsSource="{Binding Shops}"
                    BackgroundColor="Blue">
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <VerticalStackLayout>
                        <Label Text="{Binding BName}"/>
                    </VerticalStackLayout>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>
    </Grid>
</ContentView>
```

ShoppingViewModel:
```
[ObservableProperty]
        public ObservableCollection<Business> shops;

public void GetShops()
        {
            ExploreTabViewModel etvm = new ExploreTabViewModel();
            var businesses = etvm._realm.All<Business>().ToList();
            Shops = new ObservableCollection<Business>(businesses);
        }
```

Here's how I have my layout:

Views
-MainPage
-ExploreTab
-/ExploreTabs
--ShoppingTab
--View 2
-Other Tab
-Other Tab

ViewModels
-MainPageViewModel
-ExploreTabViewModel
-/ExploreTabVM
--ShoppingViewModel
--ViewModel 2
-OtherViewModels

If I try using OnAppearing with CommunityToolkit, I receive this error. I can see it most likely has something to do with my SelectedViewIndex, but I am not aware of how I can fix this.

```
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 188
   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 56
   at Microsoft.Maui.Controls.Binding.Apply(Boolean fromTarget) in D:\a\_work\1\s\src\Controls\src\Core\Binding.cs:line 114
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 529
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 469
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 391
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 365
   at Sharpnado.Tabs.TabHostView.set_SelectedIndex(Int32 value)
   at Sharpnado.Tabs.TabHostView.UpdateSelectedIndex(Int32 selectedIndex)
   at Sharpnado.Tabs.TabHostView.OnTabItemTapped(Object tappedItem)
   at Microsoft.Maui.Controls.Command.Execute(Object parameter) in D:\a\_work\1\s\src\Controls\src\Core\Command.cs:line 121
   at Sharpnado.Tabs.Effects.Droid.CommandsPlatform.ClickHandler()
   at Sharpnado.Tabs.Effects.Droid.CommandsPlatform.OnTouch(TouchEventArgs args)
   at Sharpnado.Tabs.Effects.Droid.GestureCollectors.TouchCollector.ActionActivator(Object sender, TouchEventArgs e)
   at Android.Views.View.IOnTouchListenerImplementor.OnTouch(View v, MotionEvent e) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.View.cs:line 4139
   at Android.Views.View.IOnTouchListenerInvoker.n_OnTouch_Landroid_view_View_Landroid_view_MotionEvent_(IntPtr jnienv, IntPtr native__this, IntPtr native_v, IntPtr native_e) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.View.cs:line 4080
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLL_Z(_JniMarshal_PPLL_Z callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 231
```

**Comment by roubachof** [comment]
What is the exception message ?

**Comment by PrestigiousF** [comment]
Sorry did not expect such a quick reply. Ahah

`System.Reflection.TargetInvocationException`

So I dug deeper because it had inner exceptions and I found
`Couldn't resolve the event. (Parameter EventName)`
